### ISSUE TITLE
How to install this dotfiles on Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by 2oc** [joshukraine/dotfiles#14]
Hello!
Help me. How to install this dotfiles on Ubuntu 16.04 ?

**Comment by joshukraine** [comment]
@2oc Assuming you just ran the `install.sh` script, all you need to do is remove the symlinks. Check in your home folder: `ls -la`. Then just remove each symlink that was set up by the install script. For example: `rm .vimrc`

Before you remove anything, do ensure that it is a symlink and not an actual file that's yours. 🙂

**Comment by joshukraine** [comment]
@2oc Sorry, I misread your question. I thought you were trying to UNinstall. These dotfiles are Mac-specific, so I would not recommend that you install them on Ubuntu. Check out my Linux dotfiles here: https://github.com/joshukraine/linux-dotfiles

**Comment by 2oc** [comment]
Thank you, @joshukraine
