### ISSUE TITLE
Strange Behaviour on SSH

### ISSUE THREAD

**Issue by Rahulsharma0810** [joshukraine/dotfiles#50]
when I am connected to ssh host, I am facing strange issues

- `backspace` acting as right-arrow-key.
-  clear command shows ``'tmux-256color: unknown terminal type.```

Issue showcase : http://recordit.co/wDmn99D13p

**Comment by joshukraine** [comment]
@Rahulsharma0810 Hmm, shouldn't be any issues connecting via ssh. I use these dotfiles on several different macs, and I also connect regularly to remote linux servers. If I understand your setup correctly, you have installed the dotfiles on a mac computer and you are experiencing strange behavior after connecting to a remote server, yes?

Your second bullet point seems to indicate an issue with one of the custom terminfo profiles I've included. Possibly they are not installed properly? Couple of questions:

- Did you run the install script for the dotfiles? (`install.sh`) This should have have setup all the included terminfo profiles.
- Did you set up a custom machine config for your computer? (https://github.com/joshukraine/dotfiles#machine-specific-configs)
- What type of server are you connecting to? (All mine run Ubuntu, and I've never had any issues there.)
- Could you please provide the output of this command on your mac? -> `tree -L 2 $HOME/.terminfo/`
- Also, some further info about your system in general might be helpful. (e.g. [Neofetch](https://github.com/dylanaraps/neofetch) output)

FWIW, this is my main machine:

![Screen Shot 2020-08-18 at 7 24 27 PM](https://user-images.githubusercontent.com/615841/90539477-887e4580-e188-11ea-9747-cdb1c2bd4d30.png)

**Comment by Rahulsharma0810** [comment]
@joshukraine,

I am not sure how, but the issue solved by install iterm2 integration tools.

![image](https://user-images.githubusercontent.com/9934859/90659300-2265f100-e262-11ea-98c7-d8eb15e539d5.png)

I am Providing below info, to debug this in future if someone faces the same.

1. Did you run the install script for the dotfiles? - Couple if times
2. Did you set up a custom machine config for your computer? - it's there after `install.sh`.
3. What type of server are you connecting to? - Ubuntu 

```
❯ tree -L 2 $HOME/.terminfo/
/Users/rahul/.terminfo/
├── 61
│   ├── alacritty
│   └── alacritty-direct
├── 74
│   └── tmux-256color
└── 78
    └── xterm-256color-italic

3 directories, 4 files
```

![image](https://user-images.githubusercontent.com/9934859/90660038-0747b100-e263-11ea-9708-6b73961d5ea1.png)
