### ISSUE TITLE
Tmux, CTRL + l not working

### ISSUE THREAD

**Issue by Rahulsharma0810** [joshukraine/dotfiles#51]
I found ctrl + l, to clear screen doesn't work with tmux.

```
❯ tmux 3.1b

❯ fish, version 3.1.2
```

Can you tell me how can I enable, this is a native crucial keybinding

**Comment by Rahulsharma0810** [comment]
Thanks for the course recommendation.

I like `c abbr` but most of the time I work on ssh connection with default bashrc profiles on the remote systems. so `CTRL + l` would be a great choice for me as this is native on Linux systems.

Currently, I have til/backtick as prefix.
```
unbind C-b
set-option -g prefix `
bind ` send-prefix
```
Can you quickly tell me below with work?
```
bind `-l send-keys 'C-l'
```
Thanks

**Comment by joshukraine** [comment]
@Rahulsharma0810 I'm sorry but I don't know if that will work or not. I never have any issues when connecting to ssh servers, so you may have to just sort things out by trial and error.
