### ISSUE TITLE
How do you copy paste

### ISSUE THREAD

**Issue by Rahulsharma0810** [joshukraine/dotfiles#53]
HI @joshukraine, 

I can see copy mode by Prefix + Enter, But how you select lines and copy from these configs.

Regards,
Rahul Sharma

**Comment by joshukraine** [comment]
Just press Prefix followed by left bracket (`[`). (Not simultaneously) Then you'll be in copy/paste mode, and you can navigate and select with Vim commands. For example, `Shift + v` for linewise visual mode. Then just `y` to yank.
