### ISSUE TITLE
machine-specific Brewfile

### ISSUE THREAD

**Issue by JSaterdalen** [joshukraine/dotfiles#59]
I may have missed it, but after reading through your bootstrap repo and this dotfiles repo I can't find where your machine-specific Brewfile comes into play. At what point in the install process does the script recognize it's on the family-mac and make that Brewfile available for install? 

Do you manually call that Brewfile bundle on that machine when needed?

**Comment by joshukraine** [comment]
@JSaterdalen Hey Josh, thanks for the question! Sorry for the delayed response — been traveling. 

So the way I have this set up is that the dotfiles install script doesn't actually care about the machine-specific Brewfile. The script tries to [link all the machine-specific config files](https://github.com/joshukraine/dotfiles/blob/master/install.sh#L170) based on a folder whose name matches the host name of your computer, but the Brewfile actually just gets [linked from your home directory](https://github.com/joshukraine/dotfiles/blob/master/install.sh#L139) to `$DOTFILES/Brewfile`. My assumption is that for most setups, this will be enough. 

However, if you want to add/use a machine-specific Brewfile, **the way to do that is with my [custom fish function](https://github.com/joshukraine/dotfiles/blob/master/fish/functions/bb.fish) in lieu of of the default `brew bundle` command**. Here's how:

1. Add your custom Brewfile to `$DOTFILES/machines/$HOST_NAME/Brewfile`
2. Use the provided `bb` function in lieu of `brew bundle`.

FYI, there are also `bbc` and `bbcf` functions for `brew bundle cleanup` and `brew bundle cleanup --force` respectively.

Hope that helps! I should probably have this better documented in the README. Feel free to open a PR if you like. 🙂

**Comment by JSaterdalen** [comment]
@joshukraine Cool, thanks for the insight! I ended up wanting to automate the machine specific brewfile without maintaining 3 large files. Keeping machine-specific stuff in their own file and then [appending that](https://github.com/JSaterdalen/dotfiles/blob/main/bin/bb) to the end of my base file.
