### ISSUE TITLE
How do I turn off the right side bar mini preview thing? (btw thanks for dotfiles)

### ISSUE THREAD

**Issue by letrungkien** [joshukraine/dotfiles#66]
I am not familiar with the setting and how it's called. Could you let me know how I could turn this off? It's covering the code beneath it so I can't read when I split the windows.

Thanks in advance.
![image](https://github.com/joshukraine/dotfiles/assets/8326788/0d14e00c-2036-4fe5-8e3b-0fa03758c762)

**Comment by joshukraine** [comment]
If you just want to toggle it off temporarily, use `<leader>5`. Unless you've made changes, the leader should be `<space>`. If you just press `<space>` and wait a couple of seconds, you'll see the whichkey menu come up which will show you a lot of options, including the mini.map toggle.

If you want to stop the minimap from launching at all, you can disable or tweak the relevant [autocommand](https://github.com/joshukraine/dotfiles/blob/master/lvim/.config/lvim/lua/user/autocommands.lua#L75).

For more general info on configuring the mini.map plugin, check the GitHub page: https://github.com/echasnovski/mini.map/

**Comment by letrungkien** [comment]
@joshukraine Thank you very much for the detailed instruction. I could disable the mini.map. I'll explore its feature in the future.
